// <auto-generated />
namespace SchoolDiary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class naziv_migracije : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(naziv_migracije));
        
        string IMigrationMetadata.Id
        {
            get { return "202304101305420_naziv_migracije"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
